# Source: cluster-api-aws/templates/aws-machinetemplates-control-plane.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSMachineTemplate
metadata:
  name: f5fc3b5c-ef1d-494b-8100-0e3f6da106db-control-plane
  namespace: f5fc3b5c-ef1d-494b-8100-0e3f6da106db
spec:
  template:
    spec:
      iamInstanceProfile: control-plane.cluster-api-provider-aws.sigs.k8s.io
      instanceType: t3.medium
      sshKeyName: tks-seoul
      rootVolume:
        size: 20
        type: gp2
