# Source: cluster-api-aws/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: f5fc3b5c-ef1d-494b-8100-0e3f6da106db-capi-aws
rules:
- apiGroups:
  - 'apiextensions.k8s.io'
  resources:
  - customresourcedefinitions
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
